version: '3.3'

volumes:
  pg_data:
  backend_static:

services:

  db:
    image: postgres:13.10
    env_file: ./library/.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  library:
    build:
      context: ./library/
      dockerfile: Dockerfile
    env_file: ./library/.env
    volumes:
      - backend_static:/app/static_backend
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - backend_static:/backend_static

  celery:
    build: ./library
    command: celery worker --app=library --loglevel=info
    volumes:
      - ./library:/usr/src/app
    env_file: ./library/.env
    depends_on:
      - library
      - nginx
      - redis

  redis:
    image: redis:5-alpine

  dashboard:
    build: ./library
    command:  flower -A library --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    env_file: ./library/.env
    depends_on:
      - nginx
      - redis
      - celery
