version: '3.3'

volumes:
  backend_static:

services:

  library:
    build:
      context: ./library/
      dockerfile: Dockerfile
    # env_file: ../backend/.env
    volumes:
      - backend_static:/app/static_backend
    # depends_on:
      # - db

  nginx:
    # image: nginx:1.19.3
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
      # - "9100:80"
    volumes:
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - backend_static:/backend_static

  celery:
    build: ./library
    command: celery worker --app=library --loglevel=info
    volumes:
      - ./library:/usr/src/app
    env_file: ./library/.env
    depends_on:
      - library
      - nginx
      - redis

  redis:
    image: redis:5-alpine
